### ISSUE TITLE
Repo is not HACS compliant

### ISSUE THREAD

**Issue by haakonstorm** [xannor/hass_py_set_state#1]
<img width="614" alt="Screenshot of Safari (24-11-2019, 19-22-34)" src="https://user-images.githubusercontent.com/193781/69499189-cdbe6100-0eef-11ea-8120-c4a2b9b69d4a.png">

**Comment by xannor** [comment]
Add it as a python script, it is not a custom component. I should note this in the README.

**Comment by haakonstorm** [comment]
OK, thanks, - because the previous version of the text mentioned it was possible to add this repo to HACS, which would enable upgrades et al.

**Comment by xannor** [comment]
You still can, you just have to select python script as the type of repository you are adding when you add it to HACS. If the new readme is not clear let me know and I'll try to reword it again.

**Comment by haakonstorm** [comment]
I only get options for Integration and Plugin, thats why:
<img width="463" alt="Screenshot of Safari (26-11-2019, 15-59-12)" src="https://user-images.githubusercontent.com/193781/69645061-d5a01180-1065-11ea-8a8c-8359b428aaf3.png">

**Comment by xannor** [comment]
Ahh, you must be running an old version. You will need to update HACS first.I have 0.17.4 as the latest. I dont know which version was when the different catagories were added.

Edit: I looked it up and python script support was added in 0.9.0, so I will note that in the readme.
